### ISSUE TITLE
Task create per instance

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/sintefboard#3]
The board should provide a `task create` command that we could invoke per task instance and not simply globally for all task instances.

**Comment by sdalgard** [comment]
I will dig into it.
Suggest to change the command to:
  task create [instance_name]

If instance_name is given only that instance will be started
If no name is given all will be started

**Comment by sdalgard** [comment]
Done ....

**Comment by brice-morin** [comment]
@maxleiko can you update the Kevoree side so that it take advantage of that new feature?

**Comment by maxleiko** [comment]
Yup. Doing that tomorrow morning

**Comment by maxleiko** [comment]
@brice-morin @sdalgard 
- What's the differences between `create` and `resume` ? (is it useful? why not just have a `start` command)
- Is there a command to remove an instance ?

**Comment by sdalgard** [comment]
This is actually concepts for the uC/OS task scheduler.
![capture3](https://cloud.githubusercontent.com/assets/2270169/6187920/5646f452-b38c-11e4-855b-de618ce79020.PNG)

The idea in our use is to instatntiate all tasks and create all channels as one step before actually starting any activity. Then as a second step create the tasks as a final step.
By doing this sequence we dont need to synchronize the startup.

We have not made the command "task remove". In order to do this we need to free all memory for that task. The OS does support task deletion but not freeing of memory.

**Comment by sdalgard** [comment]
Task commands is restructured
task instantiate - unchanged
task run - combines task create and task resume into one command
task stop - replaces task suspend
